aliases:
  - &install-tools
    name: Install tools
    command: |
      sudo npm install -g npm@latest

  - &restore-npm-cache
    key: dependency-cache-{{ checksum "package.json" }}

  - &save-npm-cache
    key: dependency-cache-{{ checksum "package.json" }}
    paths:
      - node_modules

  - &npm-install
    name: Install packages
    command: npm install

defaults: &defaults
  working_directory: /tmp/web
  docker:
    - image: circleci/node:10.16-stretch

version: 2

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - run: *install-tools
      - restore-cache: *restore-npm-cache
      - run: *npm-install
      - save-cache: *save-npm-cache
      - persist_to_workspace:
          root: /tmp/web
          paths:
            - .
  build_www:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/web
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: /tmp/web
          paths:
            - .
  release_www:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/web
      - run:
          name: Create docs dir from dist
          command: cp -r dist/ docs/
      - add_ssh_keys:
          fingerprints:
            - "2e:d7:94:72:02:d1:0d:1f:b8:93:ba:fb:8e:98:f2:79"
      - run: echo $REMOTE_HOSTKEY >> ~/.ssh/known_hosts
      - run:
          name: Push docs
          command: |
            git config --local user.name "Release Bot"
            git config --local user.email "dotone-www-git@dot0x01.com"
            git add ./docs/
            git commit -m "Release [ci skip]"
            git push origin master

workflows:
  version: 2
  build:
    jobs:
      - install
      - build_www:
          requires:
            - install
      - release_www:
          requires:
            - build_www
          filters:
            branches:
              only: master
